apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tictactoe
spec:
  replicas: 1
  selector:
    matchLabels:
      game: tictactoe
  template:
    metadata:
      labels:
        game: tictactoe
    spec:
      containers:
      - name: tictactoe
        image: dahankzter/tictactoe:v0.0.1
        ports:
          - containerPort: 5000
        command: ["python"]
        args: ["application.py", "--mode", "local", "--endpoint", "scylla-cluster-client.scylla.svc","--port", "8000"]

---

apiVersion: v1
kind: Service
metadata:
  name: tictactoe
spec:
  type: NodePort
  selector:
    game: tictactoe
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tictactoe-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: tictactoe
          servicePort: 5000